### ISSUE TITLE
promoter manifest: move "registries" field out to a separate YAML location

### ISSUE THREAD

**Issue by listx** [kubernetes-sigs/k8s-container-image-promoter#138]
This will improve the security posture because it would separate credentials from the image details.

**Comment by listx** [comment]
One simple idea I have is: we could just make it so that the `images:...` field can be replaced with a `images-link: path/to/images.yaml`. So overall a promoter manifest could look something like:

```
# manifest-metadata.yaml
registries:
- name: gcr.io/foo
  service-account: foo@
  src: true
- name: gcr.io/bar
  service-account: bar@
images-path: path/to/images.yaml
```

and separately in `path/to/images.yaml`:

```
images:
- name: baz
  dmap:
    "sha256:........": ["v1.0"]
```

This way, we can place the manifest-metadata.yaml in a much more restricted location (can only be approved by 2 or 3 people) and have the images yaml be in a different folder with less restricted OWNERS.

I just realize that with this change, the `renames:` field is caught in the middle. It depends on both the registries defined in the metadata and also the image name contents. I think we should just retire the whole renames logic because, while interesting and flexible, (1) we don't use it in practice (no one is asking for it, at least not any more) and (2) making renames work nicely with the above is tricky at best and I think it is a lesser priority.

/cc @justinsb @thockin
