### ISSUE TITLE
readme inconsistency related to manifests structure

### ISSUE THREAD

**Issue by bartsmykla** [kubernetes-sigs/k8s-container-image-promoter#33]
Hi, in documentation there is example manifest:
```
src: gcr.io/myproject-staging-area
registries:
- name: gcr.io/myproject-staging-area
  service-account: foo@google-containers.iam.gserviceaccount.com
- name: gcr.io/myproject-production
  service-account: foo@google-containers.iam.gserviceaccount.com
images:
- name: apple
  dmap:
    "sha256:e8ca4f9ff069d6a35f444832097e6650f6594b3ec0de129109d53a1b760884e9": ["1.1", "latest"]
- name: banana
  dmap:
    "sha256:c3d310f4741b3642497da8826e0986db5e02afc9777a2b8e668c8e41034128c1": ["1.0"]
- name: cherry
  dmap:
    "sha256:ec22e8de4b8d40252518147adfb76877cb5e1fa10293e52db26a9623c6a4e92b": ["1.0"]
    "sha256:06fdf10aae2eeeac5a82c213e4693f82ab05b3b09b820fce95a7cac0bbdad534": ["1.2", "latest"]
```
and in https://github.com/kubernetes-sigs/k8s-container-image-promoter/commit/9514603198569860ffd0e5ddc7cd7221673f2bd5 there was change of `src` to `src-registry`
