### ISSUE TITLE
Audit Defined Child Images

### ISSUE THREAD

**Issue by tylerferrara** [kubernetes-sigs/k8s-container-image-promoter#402]
#### What would you like to be added:
If a child image is defined within a sub-project's promotion manifest, it will not be seen by the Auditor since the parent image (manifest list) is under a different name. Our incoming child image [will never match](https://github.com/kubernetes-sigs/k8s-container-image-promoter/blob/master/legacy/audit/auditor.go#L244-L248) an existing child definition, because it's under a different name.

#### Example
Most manifest lists look something like this:
```
# sub-project: k8s-sub-project
- name: logger
  dmap:
    "sha256:c4151a15c8439265d98f66d25ef17964e9e975d894822a54ed7e72db78dba6c6": ["parent"]
- name: logger-amd
  dmap:
    "sha256:2c9c8df42ac7525e556bbff81aa9a62960888c69d5faad4aad408893bc95cbc9": ["child_amd"]
- name: logger-arm
  dmap:
    "sha256:a41a91e366e973da0bfd6fce44ba131d561ab435119ff7e1050d1e226a06dbda": ["child_arm"]
```
If the logger image is of `mediaType: manifest.list` (a parent image) which contains both `logger-amd` and `logger-arm` images, our Auditor does not recognize these children are actually defined within the promotion manifest. The incoming Pub/Sub message for a child image of `logger` looks like this:
```
gcr.io/k8s-sub-project/loggersha256:2c9c8df42ac7525e556bbff81aa9a62960888c69d5faad4aad408893bc95cbc9
```
If you look carefully, this image does not exist! But in actuality, this is the child image `logger-amd` we defined within the promotion manifest. Since this is how an incoming Pub/Sub child image looks like, we must widen our criteria for linking images with a promotion manifest. ​

#### Why is this needed:
Looking at the sha256 digest, instead of the fully qualified image name (FQN), the Auditor will be able to recognize incoming child images if they are define in a  promotion manifest. Not all sub-projects explicitly define child images, however for the ones that do follow this convention the verification will not require a full read of the source registry. This change has the potential to dramatically decrease the number of HTTP request send to GCR if all child images can be found in the [kubernetes/k8s.io](https://github.com/kubernetes/k8s.io/) repository. The result of this feature would reduce the number of instances the Auditor exceeds GCR Quotas and causes false alarms (Issue: [Noisy Auditor](https://github.com/kubernetes/k8s.io/issues/2364))
