### ISSUE TITLE
add --(re)strict-namespace flag to force images to be promoted within a particular namespace

### ISSUE THREAD

**Issue by listx** [kubernetes-sigs/k8s-container-image-promoter#71]
E.g., images coming from `gcr.io/foo-project/...` should only be able to be promoted as `k8s.gcr.io/foo-project/...`. That is, the top-level folder name should match `1:1`.

This check would kick in after we do the rename logic (it's still possible to rename images for production); it's just that with the flag turned on we would perform an extra check prior to promotion.

This feature could also be enforced as a field in the manifest YAML, but it's better to keep it as a flag-only thing because we don't want individual promoter manifest owners to change this setting (the binary invocation of the promoter will sit in a tightly-controlled Prow job config).

**Comment by thockin** [comment]
This is a bt more nuanced.  Specifically, images coming from `gcr.io/k8s-staging-foo-project/*` should only promote to `k8s.gcr.io/foo-project/*`.  The difference being that the "project name" in the source is embedded in the name.

Do we need to put that token into the YAML schema for promoter?  E.g.

```
registries:
- name: gcr.io/k8s-staging-foobar
  src: true
- name: us.gcr.io/k8s-artifacts-prod
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
  subdir: foobar
- name: eu.gcr.io/k8s-artifacts-prod
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
  subdir: foobar
- name: asia.gcr.io/k8s-artifacts-prod
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
  subdir: foobar
images: []
renames: []
```

or somethng?

**Comment by thockin** [comment]
Also, we need a special-case for legacy images to have the same name.

**Comment by listx** [comment]
> This is a bt more nuanced. Specifically, images coming from `gcr.io/k8s-staging-foo-project/*` should only promote to `k8s.gcr.io/foo-project/*`. The difference being that the "project name" in the source is embedded in the name.
> 
> Do we need to put that token into the YAML schema for promoter? E.g.
> 
> ```
> registries:
> - name: gcr.io/k8s-staging-foobar
>   src: true
> - name: us.gcr.io/k8s-artifacts-prod
>   service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
>   subdir: foobar
> - name: eu.gcr.io/k8s-artifacts-prod
>   service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
>   subdir: foobar
> - name: asia.gcr.io/k8s-artifacts-prod
>   service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
>   subdir: foobar
> images: []
> renames: []
> ```
> 
> or somethng?

Hmm, yes. There are many choices here.

So we want `gcr.io/k8s-staging-foobar/...` to be named `xxxx.gcr.io/k8s-artifacts-prod/foobar/...`. I think we should just make the `renames:` field smarter to reuse that part of the codebase, because this is exactly what we are doing (renaming things upon promotion under a particular namespace). The key here is that we are renaming *all* images in the manifest to be under a certain namespace.

Something like

```
renames:
  global: # <-------- optional
    from: "gcr.io/k8s-staging-foobar"
    to: "*.gcr.io/k8s-artifacts-prod/foobar"
  by-image: [] # <---------- old rename style, where each entry in the array is a list of images that should be "equivalent"
```

We would have to have checks against the `by-image` key above to make sure it respects the intent under `global`.
 
> Also, we need a special-case for legacy images to have the same name.

I think the above design can accommodate this need, with some tweaks. Each of the cases discussed here will need to be codified in the unit tests we have for renames.

**Comment by thockin** [comment]
I will leave the schema decisions to you all who have your hands in the
code.  In my mind this is not a "rename" so much as a "rebase" and the
simpler we can express that, the better.  That said, you know the impl and
I don't, so it's your call.

**Comment by listx** [comment]
> I will leave the schema decisions to you all who have your hands in the code. In my mind this is not a "rename" so much as a "rebase" and the simpler we can express that, the better. That said, you know the impl and I don't, so it's your call.

ACK

**Comment by justinsb** [comment]
I was chatting with @listx about this - I think it could be pretty accident-prone to "really" rename images, rather than just changing the subdir.

A slightly easier syntax could be to put the subdir into the registry name, which is pretty similar to what we did (accidentally) on GCS:

```
registries:
- name: gcr.io/k8s-staging-foobar
  src: true
- name: us.gcr.io/k8s-artifacts-prod/foobar
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: eu.gcr.io/k8s-artifacts-prod/foobar
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: asia.gcr.io/k8s-artifacts-prod/foobar
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
...
```
